### ISSUE TITLE
issue in file rpcserver.cpp

### ISSUE THREAD

**Issue by crptec** [SUQAORG/SUQA-CORE#15]
CAmount AmountFromValue(const Value& value)
{
    double dAmount = value.get_real();
    if (dAmount <= 0.0 || dAmount > 21000000.0)

I thing 21m is for bitcoin?

**Comment by pallas1** [comment]
Indeed. That's bad coding we inherited (it should use a macro instead of hardcoded constant). Will fix it asap. Thanks for reporting.

**Comment by pallas1** [comment]
#70dc20cc83d1409d08a1fb4f146a1d1e0a9e6830
