### ISSUE TITLE
./autogen.sh→aclocal: warning: couldn't open directory 'build-aux/m4': No such file or directory

### ISSUE THREAD

**Issue by borgeens** [SUQAORG/SUQA-CORE#18]
./autogen.sh

aclocal: warning: couldn't open directory 'build-aux/m4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.

make

make: *** [all-recursive] Error 1

**Comment by pallas1** [comment]
What if you run "./configure" before "make"?

**Comment by borgeens** [comment]
> 如果你在“make”之前运行“./configure”怎么办？

I will run ./autogen.sh first.
Then ./configure
Then make

make：*** [all-recursive]错误1

**Comment by pallas1** [comment]
Is there any error in the output of the configure command?

**Comment by borgeens** [comment]
> configure命令的输出有错误吗？

configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)

**Comment by pallas1** [comment]
./configure --disable-tests --with-incompatible-bdb --disable-shared --with-pic --with-bignum=no --with-gui=qt5 --disable-hardening CPPFLAGS=-fPIC

this is not a support forum, please head over to discord.
