### ISSUE TITLE
Swift validation bug (currently a non-issue bug)

### ISSUE THREAD

**Issue by a1i3nj03** [SUQAORG/SUQA-CORE#2]
NOTE this can/does cause the ccminer for x22i to segfault while mining with 32-bit build, and may cause undefined behavior.
A 512 bit hash is used, which is 64 bytes.
https://github.com/SUQAORG/SUQA-CORE/blob/453305d8a7951fe35b4142a8c650a0ec65daaaa1/src/algo/hashx22i.h#L68
Here the 65th byte is written to on the final call to this function
https://github.com/SUQAORG/SUQA-CORE/blob/453305d8a7951fe35b4142a8c650a0ec65daaaa1/src/algo/SWIFFTX/SWIFFTX.c#L1066
(Definition is 65 byte buffer)
https://github.com/SUQAORG/SUQA-CORE/blob/453305d8a7951fe35b4142a8c650a0ec65daaaa1/src/algo/SWIFFTX/SWIFFTX.h#L29
The call after the swift hash round overwrites the out-of-bounds buffer access (the implementation uses buffers for each stage for whatever reason) So hash-for-swift[65] is hash-for-haval[0] which is the byte accessed out-of-bounds.
https://github.com/SUQAORG/SUQA-CORE/blob/453305d8a7951fe35b4142a8c650a0ec65daaaa1/src/algo/hashx22i.h#L137
One fix would be to use a 65 byte buffer for that call, another to remove the final 64-byte write in the swift function SWIFFTSum by adding a function SWIFFTSumFinal that skips that write, otherwise using a temporary buffer, and copying it to the swift program.

**Comment by pallas1** [comment]
ccminer is fixed, see #8 for the wallet fix.
