### ISSUE TITLE
Compiling on Linux Mint 17.2

### ISSUE THREAD

**Issue by oakmaster** [SUQAORG/SUQA-CORE#25]
I get this error and I'm not a huge linux guy still learning if someone can help would be appreciated
/usr/bin/ld: libbitcoin_common.a(libbitcoin_common_a-groestl.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
libbitcoin_common.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [SUQAd] Error 1
make[2]: Leaving directory `/home/portable/Downloads/SUQA-CORE-6.0.2.2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/portable/Downloads/SUQA-CORE-6.0.2.2/src'
make: *** [all-recursive] Error 1

**Comment by pallas1** [comment]
Try this configure command:
./configure --disable-tests --with-incompatible-bdb --disable-shared --with-pic --with-bignum=no --with-gui=qt5 --disable-hardening CPPFLAGS=-fPIC
Change --with-gui to "no" if you don't need it.

**Comment by oakmaster** [comment]
Thank You that worked

**Comment by oakmaster** [comment]
I'm closing this, problem solved thanks to pallas1
